# Generated by Django 4.1.4 on 2022-12-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_alter_notes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='author',
        ),
    ]
