# Generated by Django 4.1.4 on 2022-12-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notesapp', '0007_notes_group_alter_notes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
